### ISSUE TITLE
Collect and structure data for Exogenous Variables: Wind and Con-Coop Drivers

### ISSUE THREAD

**Issue by NicoGomezAndujar** [johnwoodill/Puerto_Rico_Coop-Conf-EDA#5]
Nico - Wind Intensity (speed) raster data, cut in (hopefully 1km^2) grids. Needed in averaged monthly resolution for 2010-2019. 

Ciera - Cleanup and organize Con-Coop Drivers as the co-variates John needs.

**Comment by NicoGomezAndujar** [comment]
1)  Collect data on exogenousoceanographic data (current patterns, MLD, DOM)  and climatic indexes for the region (NAO, AMO, Caribbean index?).

**Comment by johnwoodill** [comment]
@NicoGomezAndujar Thanks. Here are the variables we also discussed last week.

Impact on fisher: Wind, Wave Height, Water Temp
Impact on fish: CHL, Sub-surface, mixed layer depth, isothermal depth.
