### ISSUE TITLE
Decide on variable that defines the intensity of coop vs conflict

### ISSUE THREAD

**Issue by johnwoodill** [johnwoodill/Puerto_Rico_Coop-Conf-EDA#6]
In the current model, the coop/conflict intensity is simply the sum across i and t. We need to think about how to define this variable for the first difference in the model so we are correctly identifying the marginal effect. This is a crucial component to ensure our predictions are correctly identified.

**Comment by NicoGomezAndujar** [comment]
So far, we are using the conflict/cooperation ratio, correct?

**Comment by johnwoodill** [comment]
@NicoGomezAndujar Yes, I think so for now. I'm a bit worried about the number of events in the east skewing the ratio, but we can discuss that later.

**Comment by johnwoodill** [comment]
Confirmed conflict/coop ratio.
